import type { Metadata } from "next";
import { BIZ_UDPGothic, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const bizudpgothic = BIZ_UDPGothic({
  weight: ["400", "700"],
  variable: "--font-biz-udpgothic",
  subsets: ["latin"],
});

const jetbrainsmono = JetBrains_Mono({
  weight: ["400", "500", "600", "700"],
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={`${bizudpgothic.variable} ${jetbrainsmono.variable}`}>
      <body>{children}</body>
    </html>
  );
}
